# Generated by Django 2.1.1 on 2018-09-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180913_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Call')),
            ],
        ),
    ]
