# Generated by Django 2.1.1 on 2018-09-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_calldetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallDetails',
            new_name='CallDetail',
        ),
    ]
