# Generated by Django 2.1.1 on 2018-09-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pricerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRuleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pricerule',
            name='fixed_end_period',
        ),
        migrations.RemoveField(
            model_name='pricerule',
            name='fixed_price',
        ),
        migrations.RemoveField(
            model_name='pricerule',
            name='fixed_start_period',
        ),
        migrations.RemoveField(
            model_name='pricerule',
            name='variable_price',
        ),
        migrations.AddField(
            model_name='priceruledetail',
            name='price_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PriceRule'),
        ),
    ]
