# Generated by Django 2.1.1 on 2018-09-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180913_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceruledetail',
            old_name='price',
            new_name='call_charge',
        ),
        migrations.AddField(
            model_name='priceruledetail',
            name='standing_charge',
            field=models.FloatField(default=0.0),
        ),
    ]
