# Generated by Django 2.1.1 on 2018-09-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180913_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
