# Generated by Django 2.1.1 on 2018-09-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180918_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
